# -*- coding: utf-8 -*-
"""FDS_W03_P01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iXr2iwdLqwZN5iWC-6NydhHOU33HpZaw
"""

print('hello world')

print("hlo")

print("i m Ved")

print("its"+"ved")

print(1000+236) #comment

print(156/36)

print(True or False)

print(True and False)

type(True)

